name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          sudo echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/your-key.pem
          sudo chmod 600 ~/.ssh/your-key.pem

      - name: Copy Files to EC2
        run: |
          sudo scp -i ~/.ssh/your-key.pem -o StrictHostKeyChecking=no -r . ubuntu@34.230.60.24:/var/www/app/

      - name: Start Application on EC2
        run: |
          sudo ssh -i ~/.ssh/your-key.pem -o StrictHostKeyChecking=no ubuntu@34.230.60.24 "cd /var/www/app && npm install && pm2 start index.js --name app"

