name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files to EC2
        run: |
          scp -i ~/.ssh/your-key.pem -o StrictHostKeyChecking=no -r . ubuntu@your-ec2-public-ip:/var/www/app/
          
      - name: Start Application on EC2
        run: |
          ssh -i ~/.ssh/your-key.pem -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip "cd /var/www/app && npm install && pm2 start index.js --name app"

